<?php

/**
 * @file
 * Functions to support theming in the Bartik theme.
 */

use Drupal\Core\Template\Attribute;
use Drupal\block\Entity\Block;
use Drupal\Core\Url;
use Drupal\Core\Form\FormStateInterface;
use Drupal\Component\Utility\Unicode;
use Drupal\Core\Menu\MenuLinkInterface;
use Drupal\Component\Plugin\Exception\PluginNotFoundException;

$theme_path = \Drupal::service('extension.list.theme')->getPath('gavias_batiz');
include_once $theme_path . '/includes/functions.php';
include_once $theme_path . '/includes/template_menu.php';
include_once $theme_path . '/includes/oembed.php';
include_once $theme_path . '/includes/contact.php';
include_once $theme_path . '/customize/fonts.php';

function gavias_batiz_preprocess_page(&$variables) {
  global $base_url;
  $theme_path = \Drupal::service('extension.list.theme')->getPath('gavias_batiz');
  $variables['#attached']['drupalSettings']['layzy_load'] = theme_get_setting('lazy_load');
  $variables['footer_first_size'] = theme_get_setting('footer_first_size');
  $variables['footer_second_size'] = theme_get_setting('footer_second_size');
  $variables['footer_third_size'] = theme_get_setting('footer_third_size');
  $variables['footer_four_size'] = theme_get_setting('footer_four_size');

  
  //Header setting -----------
  $header = 'header';
  if(theme_get_setting('default_header')){
    $header = theme_get_setting('default_header');
  }
  if(isset($variables['gva_header']) && $variables['gva_header'] && $variables['gva_header']!='_none' ){
    $header = $variables['gva_header'];
  }
  if(file_exists($theme_path . '/templates/page/' . trim($header) . '.html.twig')){
    $variables['header_skin'] = $variables['directory'] . '/templates/page/' . trim($header) . '.html.twig';
  }else{
    $variables['header_skin'] = $variables['directory'] . '/templates/page/header.html.twig';
  }
  
  $variables['preloader'] = theme_get_setting('preloader');

  $variables['theme_path'] = $base_url . '/' . $theme_path;

  //Sticky Menu setting ---------
  $variables['sticky_menu'] = '';
  if(theme_get_setting('sticky_menu') == 1){
    $variables['sticky_menu'] = 'gv-sticky-menu';
  }

  //Social setting -------------
  $custom_social_link = array();
  $custom_social_link['facebook']   = theme_get_setting('facebook');
  $custom_social_link['twitter']    = theme_get_setting('twitter');
  $custom_social_link['skype']      = theme_get_setting('skype');
  $custom_social_link['instagram']  = theme_get_setting('instagram');
  $custom_social_link['dribbble']   = theme_get_setting('dribbble');
  $custom_social_link['linkedin']   = theme_get_setting('linkedin');
  $custom_social_link['pinterest']  = theme_get_setting('pinterest');
  $custom_social_link['google']     = theme_get_setting('google');
  $custom_social_link['youtube']    = theme_get_setting('youtube');
  $custom_social_link['vimeo']      = theme_get_setting('vimeo');
  $custom_social_link['tumblr']     = theme_get_setting('tumblr');
  $variables['custom_social_link']  = $custom_social_link;

  //Login form
  $user = \Drupal::currentUser();
  if($user){
    $variables['custom_account'] = "Welcome <span class=\"text-theme\">{$user->getAccountName()}</span> (<a href=\"{$base_url}/user/logout\">Sign out</a>)";
  }

  $custom_link = array();
  $custom_link['base_url'] =  $base_url;
  $custom_link['theme_path'] = $base_url . '/' . $theme_path;
  $variables['custom_link']  = $custom_link;
}

/**
 * Implements hook_preprocess_HOOK() for HTML document templates.
 *
 * Adds body classes if certain regions have content.
 */
function gavias_batiz_preprocess_html(&$variables) {
  global $theme, $base_url;
  global $parent_root;
  $theme_path = \Drupal::service('extension.list.theme')->getPath('gavias_batiz');

  //Customize
  if(theme_get_setting('enable_panel') == '1' ){
    $current_url = $_SERVER["HTTP_HOST"] . $_SERVER["REQUEST_URI"];
    $current_url = preg_replace('/([?&])display=[^&]+(&|$)/','$2',$current_url);
    if(strpos($current_url, '?')){
       $current_url .= '&';
    }
    else{
       $current_url .= '?';
    }
    $variables['current_url'] = $current_url;
  }

  $tmp_logo = theme_get_setting('logo');
  
  $variables['site_logo'] = $tmp_logo['url'];

  $variables['theme_path'] = $base_url . '/' . $theme_path;
  
  if(theme_get_setting('customize_css') ){
    $custom_style  = preg_replace( '!/\*[^*]*\*+([^/][^*]*\*+)*/!', '', theme_get_setting('customize_css') );
    $custom_style = str_replace( array( "\r\n", "\r", "\n", "\t", '  ', '   ', '    ' ), '', $custom_style );
    $variables['customize_css'] =  $custom_style;
  }

  //--- Customize gaviasthemer ---
  $customize_styles = '';
  $json = '';

  ob_start();
  $json = \Drupal::config('gaviasthemer.settings')->get('gavias_customize');
  
  if(!$json){
    if(file_exists($theme_path . '/css/customize.json')){
      $json = file_get_contents($theme_path . '/css/customize.json');
    }
  }

  $variables['links_google_fonts'] = gavias_batiz_links_typography_font($json);
  require_once($theme_path . '/customize/dynamic_style.php');
  $customize_styles = ob_get_clean();
  $customize_styles  = preg_replace( '!/\*[^*]*\*+([^/][^*]*\*+)*/!', '', $customize_styles );
  $customize_styles = str_replace( array( "\r\n", "\r", "\n", "\t", '  ', '   ', '    ' ), '', $customize_styles );

  $variables['customize_styles'] = $customize_styles;

  //Form customize 
  $user = \Drupal::currentUser();

  if(theme_get_setting('enable_customize') == 1 &&  \Drupal::moduleHandler()->moduleExists('gaviasthemer') && ($user->hasPermission('administer gavias_customize') || $user->hasPermission('administer gavias_customize preview')) ){
    $url_customize_save = Url::fromRoute('gaviasthemer.admin.customize_save', array(), array('absolute' => TRUE))->toString();
    $variables['#attached']['drupalSettings']['gavias_customize']['save'] = $url_customize_save;  
    $url_customize_preview = Url::fromRoute('gaviasthemer.admin.customize_preview', array(), array('absolute' => TRUE))->toString();
    $variables['#attached']['drupalSettings']['gavias_customize']['preview'] = $url_customize_preview;  
    $variables['#attached']['library'][] = 'gaviasthemer/customize';
 
    $variables['#attached']['drupalSettings']['gavias_customize']['json'] = $json;

    $variables['addon_template'] = '';
    $variables['save_customize_permission'] = 'hidden';
    $variables['fonts'] = gavias_batiz_render_option_font();
    $variables['patterns'] = gavias_batiz_options_patterns();
    if(file_exists($theme_path . '/templates/addon/skins.html.twig')){
      $variables['addon_template'] = $theme_path . '/templates/addon/skins.html.twig';
    }

    if($user->hasPermission('administer gavias_customize')){
      $variables['save_customize_permission'] = 'show';
    }

    $current_url = $_SERVER["HTTP_HOST"] . $_SERVER["REQUEST_URI"];
    $current_url = preg_replace('/([?&])display=[^&]+(&|$)/','$2',$current_url);
    if(strpos($current_url, '?')){
       $current_url .= '&';
    }
    else{
       $current_url .= '?';
    }
    $variables['current_url'] = $current_url;
  }
  
  //---- End customize gavias themer ---

  $skin = 'default';
  $skin = theme_get_setting('theme_skin');
  if(isset($_GET['gvas']) && $_GET['gvas']){
    $skin = $_GET['gvas'];
  }
  if(empty($skin)){
    $skin = 'default';
  }

  if(\Drupal::service('module_handler')->moduleExists('gavias_hook_themer')){
    $abs_url_config = Url::fromRoute('gavias_hook_themer.ajax_views', array(), array('absolute' => FALSE))->toString(); 
  }else{
    $abs_url_config = '';
  }
  $variables['#attached']['drupalSettings']['gavias_load_ajax_view'] = $abs_url_config;

  $variables['#attached']['library'][] = 'gavias_batiz/gavias_batiz.skin.' . $skin;
  // Add information about the number of sidebars.
  if (!empty($variables['page']['sidebar_first']) && !empty($variables['page']['sidebar_second'])) {
    $variables['attributes']['class'][] = 'layout-two-sidebars';
  }
  elseif (!empty($variables['page']['sidebar_first'])) {
    $variables['attributes']['class'][] = 'layout-one-sidebar';
    $variables['attributes']['class'][] = 'layout-sidebar-first';
  }
  elseif (!empty($variables['page']['sidebar_second'])) {
    $variables['attributes']['class'][] = 'layout-one-sidebar';
    $variables['attributes']['class'][] = 'layout-sidebar-second';
  }
  else {
    $variables['attributes']['class'][] = 'layout-no-sidebars';
  }
  
  if(theme_get_setting('preloader') == '1'){
    $variables['attributes']['class'][] = 'js-preloader';
  }else{
    $variables['attributes']['class'][] = 'not-preloader';
  }

  if(theme_get_setting('site_layout') == 'boxed'){
    $variables['attributes']['class'][] = 'boxed';
  }
  $layout = 'none';
  $body_background = 'dark';
  if ($node = \Drupal::request()->attributes->get('node')) {
    if(is_object($node)){
      if($node->hasField('gva_node_layout')){
        $layout = $node->get('gva_node_layout')->value;
      }
      if($node->hasField('gva_body_background')){
        if($node->get('gva_body_background')->value){
          $body_background = $node->get('gva_body_background')->value;
        }
      }
    }  
  }
  $variables['attributes']['class'][] = 'layout-page-' . $layout;
  $variables['attributes']['class'][] = 'body-background-' . $body_background;
}

/**
 * Implements hook_preprocess_HOOK() for maintenance-page.html.twig.
 */
function gavias_batiz_preprocess_maintenance_page(&$variables) {
  if (!$variables['db_is_active']) {
    $variables['site_name'] = '';
  }
}

/**
 * Implements hook_preprocess_HOOK() for block.html.twig.
 */
function gavias_batiz_preprocess_block(&$variables) {
  // Add a clearfix class to system branding blocks.
  if ($variables['plugin_id'] == 'system_branding_block') {
    $variables['attributes']['class'][] = 'clearfix';
    $tmp_logo = theme_get_setting('logo');
    $variables['setting_logo'] = $tmp_logo['use_default'];
  }
} 

function gavias_batiz_preprocess_block__system_breadcrumb_block(&$variables){
  $styles = array();
  $bg_image = '';//base_path() . 'images/breadcrumb.jpg';
  $bg_color = '#FFF';
  $bg_position = 'center center';
  $bg_repeat = 'no-repeat';
  $text_style = 'text-dark';
  
  if (!empty($variables['elements']['#id'])) {
    $block = Block::load($variables['elements']['#id']);
    if($variables['plugin_id'] == 'system_breadcrumb_block'){
      $_id = $variables['elements']['#id'];
      $breadcrumb_background_color = $block->getThirdPartySetting('gaviasthemer', 'breadcrumb_background_color');
      $breadcrumb_background_position = $block->getThirdPartySetting('gaviasthemer', 'breadcrumb_background_position');
      $breadcrumb_background_repeat = $block->getThirdPartySetting('gaviasthemer', 'breadcrumb_background_repeat');
      $breadcrumb_color_style = $block->getThirdPartySetting('gaviasthemer', 'breadcrumb_color_style');
      $breadcrumb_background_image_path = \Drupal::config('gaviasthemer.settings')->get('breadcrumb_background_image_path_' . $_id);
      if($breadcrumb_color_style){
        $text_style = $breadcrumb_color_style;
      }
      if($breadcrumb_background_color){
        $bg_color = $breadcrumb_background_color;
      }
      if($breadcrumb_background_position){
        $bg_position = $breadcrumb_background_position;
      }
      if($breadcrumb_background_repeat){
        $bg_repeat = $breadcrumb_background_repeat;
      }
      if($breadcrumb_background_image_path){
        $bg_image = \Drupal::service('file_url_generator')->generateAbsoluteString($breadcrumb_background_image_path);
      }
    }
  }

  $variables['attributes']['class'][] = $text_style;
  $styles[] = "background-color: {$bg_color};";
  if($bg_image){
    $styles[] = "background-image: url('{$bg_image}');";
  }  
  $styles[] = "background-position: {$bg_position};";
  $styles[] = "background-repeat: {$bg_repeat};";
  $variables['custom_style'] = implode('', $styles);
}

function gavias_batiz_preprocess_image(&$variables) {
  global $base_url;
  if(theme_get_setting('lazy_load')=='on'){
    if(isset($variables['attributes']['src'])){
      $variables['attributes']['data-src'] = $variables['attributes']['src'];
      $variables['attributes']['class'][] = 'unveil-image';
      $variables['attributes']['src'] = '';//base_path() . \Drupal::service('extension.list.theme')->getPath('gavias_batiz') .'/images/lazy_load.png';
    }
  }else{
    if (isset($variables['attributes']['width']) && isset($variables['attributes']['height'])) {
      unset($variables['attributes']['width']);
      unset($variables['attributes']['height']);
    }
  }
}

/**
 * Implements hook_preprocess_HOOK() for page templates.
 */
function gavias_batiz_preprocess_page_title(&$variables) {
  // Since the title and the shortcut link are both block level elements,
  // positioning them next to each other is much simpler with a wrapper div.
  if (!empty($variables['title_suffix']['add_or_remove_shortcut']) && $variables['title']) {
    // Add a wrapper div using the title_prefix and title_suffix render
    // elements.
    $variables['title_prefix']['shortcut_wrapper'] = array(
      '#markup' => '<div class="shortcut-wrapper clearfix">',
      '#weight' => 100,
    );
    $variables['title_suffix']['shortcut_wrapper'] = array(
      '#markup' => '</div>',
      '#weight' => -99,
    );
    // Make sure the shortcut link is the first item in title_suffix.
    $variables['title_suffix']['add_or_remove_shortcut']['#weight'] = -100;
  }
}

/**
 * Implements hook_theme_suggestions_HOOK_alter() for form templates.
 */
function gavias_batiz_theme_suggestions_form_alter(array &$suggestions, array $variables) {
  if ($variables['element']['#form_id'] == 'search_block_form') {
    $suggestions[] = 'form__search_block_form';
  }
}

/**
 * Implements hook_form_alter() to add classes to the search form.
 */
function gavias_batiz_form_alter(&$form, \Drupal\Core\Form\FormStateInterface $form_state, $form_id) {
  if (in_array($form_id, ['search_block_form', 'search_form'])) {
    $key = ($form_id == 'search_block_form') ? 'actions' : 'basic';
    if (!isset($form[$key]['submit']['#attributes'])) {
      $form[$key]['submit']['#attributes'] = new Attribute();
    }
    $form[$key]['submit']['#attributes']->addClass('search-form__submit');
  }
}

function gavias_batiz_theme_suggestions_page_alter(array &$suggestions, array $variables) {
  if ($node = \Drupal::request()->attributes->get('node')) {
    if(is_object($node)){
      if($node->hasField('gva_node_layout')){
        $layout = $node->get('gva_node_layout')->value;
        $variables['attributes']['class'][] = $layout;
        if($layout){
          array_splice($suggestions, 1, 0, 'page__layout__' . $layout);
        }else{
          array_splice($suggestions, 1, 0, 'page__node__' . $node->getType());
        } 
      }else{
        array_splice($suggestions, 1, 0, 'page__node__' . $node->getType());
      }
    }else{
      array_splice($suggestions, 1, 0, 'page__node__full');
    }
  }
}

function gavias_batiz_theme_suggestions_field_alter(&$suggestions, $variables) {
  	$suggestions[] = 'field__' . 
  	$variables['element']['#field_name'] . '__' . 
  	$variables['element']['#view_mode'];
}

// Views
function gavias_batiz_preprocess_views_view_unformatted__taxonomy_term(&$variables){
   $current_uri = \Drupal::request()->getRequestUri();
   $url = \Drupal::service('path.current')->getPath();
   $arg = explode('/', $url);
}

function gavias_batiz_preprocess_username(&$variables){
   $account = $variables['account'];
   if($account->hasField('field_full_name')){
      $field_full_name = $account->get('field_full_name');
   }
}

function gavias_batiz_preprocess_views_view_grid(&$variables) {
   $view = $variables['view'];
   $rows = $variables['rows'];
   $style = $view->style_plugin;
   $options = $style->options;
   $variables['gva_masonry']['class'] = '';
   $variables['gva_masonry']['class_item'] = '';
   $array_class = preg_split('/ /', $options['row_class_custom']);
   if(in_array('masonry', $array_class) ){
      $variables['gva_masonry']['class'] = 'post-masonry-style row';
      $variables['gva_masonry']['class_item'] = 'item-masory';
   }
}

function gavias_batiz_preprocess_views_view(&$variables) {
   global $gva_node_index;
   $gva_node_index = 0;
}

//Functions
global $gva_node_index;
function gavias_batiz_preprocess_node(&$variables) {
  global $gva_node_index;
  $gva_node_index = $gva_node_index + 1;
  $variables['gva_node_index'] = $gva_node_index;
  
  $date = $variables['node']->getCreatedTime();
  $variables['date'] = date( 'M', $date) . ' ' . t(date( 'd', $date));

  if ($variables['teaser'] || !empty($variables['content']['comments']['comment_form'])) {
    unset($variables['content']['links']['comment']['#links']['comment-add']);
  }
  $date_ago = \Drupal::service('date.formatter')->formatTimeDiffSince($date);
  $variables['date_ago'] = $date_ago . t(' ago');
  if ($variables['node']->getType() == 'article') {
      $node = $variables['node'];
      if($node->hasField('comment')){
        $variables['comment_count'] = $node->get('comment')->comment_count;
      }
      $post_format = 'standard';
      try{
         $field_post_format = $node->get('field_post_format');
         if(isset($field_post_format->value) && $field_post_format->value){
            $post_format = $field_post_format->value;
         }
      }catch(Exception $e){
         $post_format = 'standard';
      }
      $iframe = '';
      $variables['post_format'] = $post_format;

    // video content type
  }elseif($variables['node']->getType() == 'video'){
    $iframe = '';
    $node = $variables['node'];
    try{
      $field_post_embed = $node->get('field_video_embed');
      if(isset($field_post_embed->value) && $field_post_embed->value){
        $autoembed = new AutoEmbed();
        $iframe = $autoembed->parse($field_post_embed->value);
      }else{
        $iframe = '';
      }
    }
    catch(Exception $e){
       $iframe = '';
    }
    $variables['gva_iframe'] = $iframe;
  }
}

function gavias_batiz_preprocess_node__article(&$variables) {
  $view_mode = $variables['view_mode']; 
  $allowed_view_modes = ['full']; 
  if(in_array($view_mode, $allowed_view_modes)) {
    $allowed_regions = ['related_content'];
    gavias_batiz_add_regions_to_node($allowed_regions, $variables);
  }
}

function gavias_batiz_preprocess_user(&$variables) {
  	$allowed_regions = ['user_content'];
  	gavias_batiz_add_regions_to_node($allowed_regions, $variables);
}

function gavias_batiz_preprocess_comment(&$variables){
   $date = $variables['comment']->getCreatedTime();
  	$variables['created'] = date( 'j F Y', $date);
}

function gavias_batiz_preprocess_field(&$variables, $hook) {
  	$element = $variables['element'];
}  

function gavias_batiz_preprocess_breadcrumb(&$variables){
  	$variables['#cache']['max-age'] = 0;
  	$request = \Drupal::request();
  	$title = '';
  	if ($route = $request->attributes->get(\Drupal\Core\Routing\RouteObjectInterface::ROUTE_OBJECT)) {
    	$title = \Drupal::service('title_resolver')->getTitle($request, $route);
  	}
  	if($variables['breadcrumb']){
     	foreach ($variables['breadcrumb'] as $key => &$value) {
      	if($value['text'] == 'Node'){
        		unset($variables['breadcrumb'][$key]);
      	}
    	}
    	if(!empty($title)){
      	$variables['breadcrumb'][] = array(
          	'text' => ''
      	);
      	$variables['breadcrumb'][] = array(
          	'text' => $title
      	);
    	}  
  	}
}

// Menu
function gavias_batiz_preprocess_menu__main(&$variables) {
  	$variables['attributes']['class'][] = 'clearfix';
  	$language =  \Drupal::languageManager()->getCurrentLanguage()->getID();
  	$languagesAll =  \Drupal::languageManager()->getLanguages();
  	foreach ($variables['items'] as &$item) {
   	$menu_link_attributes = _gavias_batiz_attributes_get_attributes($item['original_link']);
    	if (count($menu_link_attributes)) {
	      $url_attributes = $item['url']->getOption('attributes') ?: [];
	      $attributes = array_merge($url_attributes, $menu_link_attributes);
	      $item['url']->setOption('attributes', $attributes);
	      $item['attributes']['gva_class'] = (isset($attributes['gva_class']) && $attributes['gva_class']) ? trim($attributes['gva_class']): '';
	      $item['attributes']['gva_icon'] = (isset($attributes['gva_icon']) && $attributes['gva_icon']) ? trim($attributes['gva_icon']): '';
	      $item['attributes']['gva_layout'] = (isset($attributes['gva_layout']) && $attributes['gva_layout']) ? $attributes['gva_layout']: '';
	      $item['attributes']['gva_layout_columns'] = (isset($attributes['gva_layout_columns']) && $attributes['gva_layout_columns']) ? $attributes['gva_layout_columns']: 4;
	      if(count($languagesAll) > 1){
	        	$item['attributes']['gva_block'] = (isset($attributes['gva_block_' . $language]) && $attributes['gva_block_'. $language]) ? $attributes['gva_block_'. $language]: '';
	        	if(isset($attributes['gva_block_' . $language]) && $attributes['gva_layout']=='menu-block'){
	          	$item['gva_block_content'] = gavias_batiz_render_block($attributes['gva_block_' . $language]);
	        	}
	      }else{
        		$item['attributes']['gva_block'] = (isset($attributes['gva_block']) && $attributes['gva_block']) ? $attributes['gva_block']: '';
        		if(isset($attributes['gva_block']) && $attributes['gva_layout']=='menu-block'){
          		$item['gva_block_content'] = gavias_batiz_render_block($attributes['gva_block']);
        		}
      	}
 		}
	}
}

function _gavias_batiz_attributes_get_attributes(MenuLinkInterface $menu_link_content_plugin) {
  	$attributes = [];
  	try {
    	$plugin_id = $menu_link_content_plugin->getPluginId();
  	}
  	catch (PluginNotFoundException $e) {
    	return $attributes;
  	}
  	if (strpos($plugin_id, ':') === FALSE) {
    	return $attributes;
  	}
  	list($entity_type, $uuid) = explode(':', $plugin_id, 2);

  	if ($entity_type == 'menu_link_content') {
    	$entity = \Drupal::entityTypeManager()->getStorage('menu_link_content')->loadByProperties(['uuid' => $uuid]);
    	if (count($entity)) {
      	$entity_values = array_values($entity)[0];
      	$options = $entity_values->link->first()->options;
      	$attributes = isset($options['attributes']) ? $options['attributes'] : [];
    	}
  	}
  	return $attributes;
}
